### PR TITLE
Make migrations respect custom db_table name for user model

### PR DESCRIPTION
**Pull request by stevelacey**

### CODE REVIEW

**Comment by justquick** [comment]
what issue is this trying to solve? patching older migrations is scary

**Comment by stevelacey** [comment]
@justquick the migrations failed if you had a custom User model class/dbname I forget which, if you don't, the migrations run the same

**Comment by justquick** [comment]
try the new style migrations in master

**Comment by stevelacey** [comment]
You should probably bump the major version number since this will break everyone's south migrationhistory...

**Comment by stevelacey** [comment]
Also, will Django migrations sit well with south migrations at all?

**Pull request closed without merging**
