### PR TITLE
Use supported versions of Django

### LINKED ISSUE #308: Django 1.10 removes django.conf.urls.patterns (deprecated in 1.8)
urls.py starts with:

``` python
try:                                                                               
    from django.conf.urls import url, patterns                                     
except ImportError:                                                                
    from django.conf.urls.defaults import url, patterns                                                                                      
```

`django.conf.urls.patterns` is removed in Django 1.10, so the exception handler tries to use the even older `django.conf.urls.defaults`, leading to an `ImportError` on Django 1.10. Changing to 

``` python
try:                                                                               
    from django.conf.urls import url                                    
except ImportError:                                                                
    from django.conf.urls.defaults import url, patterns
```

works in 1.10, but could cause problems on < 1.8.

Maybe change at the bottom of urls.py from:

``` python
if django.VERSION[:2] < (1, 9):                                                    
    urlpatterns = patterns('', *urlpatterns)
```

to

``` python
if django.VERSION[:2] < (1, 9):       
    try:
        from django.conf.urls import patterns
    except ImportError:
        from django.conf.urls.defaults import patterns                                         
    urlpatterns = patterns('', *urlpatterns)
```

### PR DESCRIPTION
**Pull request by jsma**
This PR updates the code to only support versions of Django that are supported upstream (currently 1.8.x, 1.9.x and 1.10x).

This should fix #308 is a more robust replacement of #311.

### CODE REVIEW

**Comment by murdav** [comment]
Thanks! Let's hope it will be merged soon.

**Comment by santiagomalter** [comment]
Thanks @jsma !

Hope it'll be merged soon as well :)

**Comment by auvipy** [comment]
https://github.com/justquick/django-activity-stream/pull/334

**Comment by auvipy** [comment]
closing in favor of https://github.com/justquick/django-activity-stream/pull/334 and other old pr's which addressed some of this pr

**Pull request closed without merging**
