### PR TITLE
Fix wagtail

### LINKED ISSUE #267: Not compatible with Wagtail
Using this with Wagtail CMS can cause errors when using registry.register with a wagtail Page. 

https://github.com/torchbox/wagtail/issues/1852

Very similar to #48

*Edited - workaround wasn't really a workaround

### PR DESCRIPTION
**Pull request by bufke**
Refactors registry.py a bit.
Removes support for Django<1.7.
Fixes the returned array in setup_generic_relations BUT I'm still not sure what this gets used for.
Adds option to disable setting up the generic relation when registering a model.
Fixes #267

### CODE REVIEW

**Comment by bufke** [comment]
Understandable if you don't want to remove old django version support  - but I don't think we support all these versions anyway. Clearly that function doesn't work in 1.8 as it was intended. I'd recommend just supporting 1.7 and 1.8 at this point. I could possibly add some more unit tests.

**Comment by auvipy** [comment]
1.8 and 1.9 only at this point.

**Comment by justquick** [comment]
going to put a pin in this. im not quite ready to deprecate <1.7 yet

**Comment by auvipy** [comment]
@justquick I will be happy to send a PR for that if you allow :)

**Comment by bufke** [comment]
I rebased the patch off the current master. This pull request is no longer needed. See https://github.com/justquick/django-activity-stream/pull/295

**Pull request closed without merging**
