### PR TITLE
Replace problamatic CharField GFKs with PositiveInterField fields.

### PR DESCRIPTION
**Pull request by Shanto**
Hi,

I just noticed an error that when you try to use any Django feature that joins GFK enabled models with other models (e.g. having GenericRelation defined on that model with some related_query_name), it produces an SQL error (PostgreSQL).

Let's take this example model:

``` python
class Post(models.Model):
    content = models.TextField(blank=True, null=True)
    position = models.PositiveSmallIntegerField(default=0, blank=True, editable=False)
    action_set = GenericRelation('actstream.Action', object_id_field='action_object_object_id', content_type_field='action_object_content_type', related_query_name='post')
```

We are using https://docs.djangoproject.com/en/1.8/ref/contrib/contenttypes/#reverse-generic-relations here with a related_query_name defined to help sorting/filtering activity streams based on this generic related model (Post) attributes. At this point, a query like below would produce some SQL error:

``` python
target_stream(another_object).order_by('post__position')
```

The error produced, in particular by PostgreSQL backend is:

```
operator does not exist: character varying = integer
```

Further investigation reveals that because you are using CharField for GenericForeignKey's PK/ID part, and because by convention other Django models use PositiveIntegerField for their primary keys, Django's SQL compiler is NOT type casting the JOIN clause. Thus, the JOIN is failing from SQL backend due to an attempt to JOIN by (varchar == int) clause.

I have successfully mitigated this issue by replacing your CharField definitions with PositiveIntegerField definitions. So, please have a look at my commit and let's discuss if there's any compelling reason to stick to CharFields.

Thanks,
Shanto

### CODE REVIEW

**Comment by Shanto** [comment]
Please note, I discarded my previous pull request on the same topic which was not complete. Please ignore that one and consider this one here. Thanks.

**Comment by justquick** [comment]
this was to fix #40 and have the maximum possible compatibility with other apps that could use any of int/char/uuid fields. i tried to make it 80% compatible with existing apps but you have hit the missing %20 with the post__position ordering clause. i bet there's a way to fix this using raw sql but since it's such a specific use case i dont see how it could be made generic enough to be included here. thoughts?

**Comment by Shanto** [comment]
Sorry that I didn't take into account your compatibility considerations in rush. Now I realize that this change is no longer needed or relevant– in fact, it would create more issues than fixing.

The source of problem is elsewhere. Seems like it can be fixed by either 1) having Django [contenttypes] developers fix it, or 2) until then work around with some custom PostgreSQL operator [on a project by project basis].

**Comment by Shanto** [comment]
Just an update! I did some research and it seems like having Django ORM fixed for this particular issue is not an easy or quick job. See https://code.djangoproject.com/ticket/20271#comment:7

Until it's fixed by Django team, do you see any easy and clean workaround?

- Even if Django team fixes this in far future, typecasting on PostgreSQL is an expensive operation for large dataset. Developers are aware of this and might not agree to compromise on performance. So, ultimately the recommendation would be to match object_id/fk types.
- Changing app models' PK to char/text type fields [to match actstream model definitions] would affect working codes elsewhere [including performance issues]. Moreover, for foreign apps, this not even an option without maintaining my own forks.
- I am holding from adding custom operators on PostgreSQL due to the same reasons.

See http://dba.stackexchange.com/questions/82511/how-to-enable-implicit-casts-in-postgresql-9-2#comment148718_82511 and http://grokbase.com/t/postgresql/pgsql-general/08adfz9c9v/bug-4078-error-operator-does-not-exist-numeric-character-varying#20081014hdv7hrlqfngjpimyinv3chuqrm.

**Comment by Shanto** [comment]
Hi, would you be open to deciding on these fields at runtime– based on some settings key? E.g. if some key is set, then we could override things, otherwise keep using CharFields? Thus, 100% of your users will have both options open. Let me know and I will prepare a push request. Thanks.

**Comment by justquick** [comment]
runtime options make it hell for things like migrations and the extra code to support both types

**Comment by justquick** [comment]
@Shanto im open to it so give it a try here and ill review

**Comment by pypetey** [comment]
This problem appeared to me today. I've migrated from SQLITE to PostgreSQL and then development environment crashed.

I could only fix everything by - applying your patch and recreating tables of activity stream (I had this convenience that my application is new and does not contain any data yet). 

It would be awesome if it could be somehow merged.

**Comment by tonythomas01** [comment]
This is really weird - its still happening with postgres and django 1.11. Someone should fix this soon :-( please

**Comment by SushilShrestha** [comment]
I am having same issue but with uuid field as primary key. (postgres 9.6.3 and django 1.11).

**Comment by auvipy** [comment]
@slurms do you have any insight to fix this ?

**Comment by tonythomas01** [comment]
We applied @Shanto s patch on a fork, and you have it here - https://github.com/3YOURMIND/django-activity-stream

**Comment by slurms** [comment]
@auvipy I can't think of anything off-hand that might fix it easily. The only thing that might be useful for this (and possibly other things) is allowing the model to be swappable and doing something similar to a custom user model: we supply an abstract base class to inherit from, and have a default implementation that covers most use cases, but allows others to customize it in their own apps to their liking. This would include things like having the activity items stick around after object deletions (#346), customising the way the data field is constructed, etc.

**Comment by auvipy** [comment]
that should be the move then, I will start work on achieving the initial goals

**Comment by slurms** [comment]
:+1: let me know if you'd like some help, i can probably spare some time to help fix this

**Comment by auvipy** [comment]
I have started work on abstract base model and swappable model settings based on an old abandoned pr https://github.com/justquick/django-activity-stream/pull/309. feel free to review and put your inputs there #387

**Pull request closed without merging**
