### PR TITLE
Attempt to use Django JSONField if Available

### PR DESCRIPTION
**Pull request by dstarner**
Attempts to solve #472 by importing the `JSONField from `django.db` if possible. This also cleans up the import logic a little bit to just iterate over a list of possible choices, instead of nesting deeply like it was before - or like it was suggested. I just threw together a `nestedtuple` that seemed somewhat organized, let me know if you have feedback to make it better.

### CODE REVIEW

**Comment by dstarner** [comment]
@justquick let me know what you think. This is partially what is blocking me from being able to use `django-activity-stream` so I'd like to get this in ASAP, even if you have change requests that I have to clean up.

**Review by auvipy — CHANGES_REQUESTED** [review]
CI on mysql might be failing due to version conflicts, can you check the failures please?

**Comment by dstarner** [comment]
Yea, will do. I'm confused @auvipy , do I need to explicitly tell it to install one or the other dependent JSONField libraries in the older versions? How did this work before if not explicitly defined?

**Comment by auvipy** [comment]
> Yea, will do. I'm confused @auvipy , do I need to explicitly tell it to install one or the other dependent JSONField libraries in the older versions? How did this work before if not explicitly defined?

I think yes. you should try to fall back into the older version

**Comment by dstarner** [comment]
I don't know how to make sense of this error, seeing as I didn't touch any requirements files that would define this. Could I get some assistance or understanding please?

```
ERROR: Double requirement given: Django<3.2,>=3.1 (already in Django<3.1,>=3.0, name='Django')
```

**Comment by oyla12** [comment]
My understandig of Travis CI and GitHub is really not extensive, but I need this here getting my project running on Django 3 to.
I found in the `.tox` file the following section. For me it seems like an double entry. But it exists since 44e26c2  about 7 month ago?

```
deps =
    coverage>=4.5.1
    django22: Django>=2.2,<3.0
    django30: Django>=3.0,<3.1
    django30: Django>=3.1,<3.2
```

Maybe it helps to rename the last one to `django31` (however it works here)

**Comment by lociii** [comment]
This has all been resolved in the now merged #474

**Pull request closed without merging**
