### PR TITLE
Django Postgresql JSONField Support

### PR DESCRIPTION
**Pull request by justquick**
Need to start supporting django.contrib.postgres.fields.JSONField in Django>=1.9

https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/#jsonfield

A lot of the deep JSON queries seem really awesome and when used to denormalize data could fix problems like #281

So far this is just the start of postgres jsonb work. Some of the test cases are broken and this needs docs.

### CODE REVIEW

**Comment by prydie** [comment]
What's the progress on this effort? I would very much like to remove the dependency on `django-jsonfield` given it is currently unmaintained and there are `RemovedInDjango110Warning`s raised when using it with 1.9.

Happy to lend a hand if needed.

**Comment by spac3-monkey** [comment]
Hi, 
I'm very interested in removing the `django-jsonfield` package. Need any help getting this done?

**Comment by auvipy** [comment]
django-jsonfield can be useful for backends other then pqsql. so no need to remove it. meanwhile new maintainers have revived the porject.

**Comment by auvipy** [comment]
https://github.com/dmkoch/django-jsonfield how about switching to this package?

**Comment by kbussell** [comment]
I have created https://github.com/kbussell/django-jsonfield-compat to be a compatibility layer between django-jsonfield and Django's native `JSONField`. See #339

**Pull request closed without merging**
